name: Reusable WF - Release

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

defaults:
  run:
    shell: bash

jobs:

  build-test-package:
    uses: "./.github/workflows/build-test-package.yml"
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      build-type: "release"

  create-release:
    needs: ['build-test-package']
    runs-on: ubuntu-latest
    steps:

    - name: Download Artifacts
      uses: actions/download-artifact@v3

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ inputs.version }}
        commit: ${{ github.sha }}
        name: "Howso Engine ${{ inputs.version }}"
        artifactErrorsFailBuild: true
        generateReleaseNotes: true
        makeLatest: legacy
        artifacts: howso-engine-*/howso-engine-*.tar.gz
        artifactContentType: application/gzip
